blue button: medical records
caregiver: caregiver benefits
champ va: champva
champ: champva
chapter 31: chapter 31 veteran readiness and employment
chapter 35: chapter 35 dependents educational assistance
claims: claim status
coe: certificate of eligibility
dd 214: dd214
dd-214: dd214
dea: dependents educational assistance
dic: survivors pension and dic
disability: va disability
disability claim: 21-526ez
education: va education
file a claim: 21-526ez
foia: freedom of information act personal records
forms: va forms
id: id card
jobs: jobs careers
pharmacy: pharmacy medications
quick submit: quicksubmit
tdiu: individual unemployability
travel claim: travel reimbursement
travel pay: travel reimbursement
vr&e: veteran readiness and employment
vre: veteran readiness and employment
