# frozen_string_literal: true

require 'mms/data_formatting'

module SurvivorsBenefits
  module StructuredData
    module V2025
      class StructuredDataService
        include SurvivorsBenefits::StructuredData::V2025::Section01
        include SurvivorsBenefits::StructuredData::V2025::Section02
        include SurvivorsBenefits::StructuredData::V2025::Section03
        include SurvivorsBenefits::StructuredData::V2025::Section04
        include SurvivorsBenefits::StructuredData::V2025::Section05
        include SurvivorsBenefits::StructuredData::V2025::Section06
        include SurvivorsBenefits::StructuredData::V2025::Section07
        include SurvivorsBenefits::StructuredData::V2025::Section08
        include SurvivorsBenefits::StructuredData::V2025::Section09
        include SurvivorsBenefits::StructuredData::V2025::Section10
        include SurvivorsBenefits::StructuredData::V2025::Section11
        include SurvivorsBenefits::StructuredData::V2025::Section12
        include Mms::DataFormatting

        attr_reader :form
        attr_accessor :fields

        FIELDS_PATH = Rails.root.join(
          'modules',
          'survivors_benefits',
          'app',
          'services',
          'survivors_benefits',
          'structured_data',
          'V2025',
          'fields.yaml'
        ).freeze

        # V2025: CB_CL_MARR2_ENDED_OTHEREXPLAIN is generated by the section 5 helper but IBM expects
        # the key without the CB_ prefix.
        IRREGULAR_FIELD_TRANSFORMS = {
          'CB_CL_MARR2_ENDED_OTHEREXPLAIN' => 'CL_MARR2_ENDED_OTHEREXPLAIN'
        }.freeze

        def initialize(form)
          @form = form
          @fields = YAML.load_file(FIELDS_PATH)
        end

        def build_structured_data
          build_section1
          build_section2
          build_section3
          build_section4
          build_section5
          build_section6
          build_section7
          build_section8
          build_section9
          build_section10
          build_section11(form['bankAccount'])
          build_section12
          fill_veteran_ssn_reference_fields
          transform_booleans(fields)
          transform_nils_to_empty_strings(fields)
          transform_irregular_fields
          fields
        end

        ##
        # Build the name fields from the form data.
        # used by Section01 and Section02
        # @param name [Hash]
        # @param individual [String] - The prefix for the field keys (e.g., "VETERAN", "CLAIMANT")
        def merge_name_fields(name, individual)
          if name && %w[VETERAN CLAIMANT].include?(individual)
            name = build_name(name)
            fields.merge!(
              {
                "#{individual}_NAME" => name[:full],
                "#{individual}_FIRST_NAME" => name[:first],
                "#{individual}_MIDDLE_INITIAL" => name[:middle_initial],
                "#{individual}_LAST_NAME" => name[:last]
              }
            )
          end
        end

        def fill_veteran_ssn_reference_fields
          ssn = form['veteranSocialSecurityNumber']
          # V2025 form has 8 SSN reference fields (V2022 had 9).
          (1..8).each { |i| fields["VETERAN_SSN_#{i}"] = ssn }
        end

        def transform_irregular_fields
          fields.transform_keys!(IRREGULAR_FIELD_TRANSFORMS)
        end
      end
    end
  end
end
