# frozen_string_literal: true

module BenefitsClaims
  module Constants # rubocop:disable Metrics/ModuleLength
    CLAIM_TYPE_LANGUAGE_MAP = {
      'Death' => 'expenses related to death or burial'
    }.freeze

    # These are evidence requests that should not be displayed to the user when:
    # - `cst_suppress_evidence_requests_website` feature flag is enabled
    # - `cst_suppress_evidence_requests_mobile` feature flag is enabled
    # See https://va.ghe.com/software/va.gov-team/issues/126870
    SUPPRESSED_EVIDENCE_REQUESTS = [
      'Admin Decision',
      'ADMINCOD',
      'Attorney Fee',
      'Attorney Fee Release',
      'Awaiting Upload of Hearing Transcript',
      'Delayed BDD Exam Requests',
      'Exam Request - Processing',
      'Exam Review - Not Performed',
      'Exam Review - Partially Complete',
      'IT Ticket-Exam Control Issue',
      'ND Additional Action Required',
      'Pending Completion of Concurrent EP',
      'Rating Extraschedular Memorandum',
      'Records Research Task',
      'Resolution of Pending Rating EP',
      'RO Research Coordinator Review',
      'Second Signature',
      'Secondary Action Required',
      'Stage 2 Development' # Not currently used by VBMS but will eventually replace `Secondary Action Required`
    ].freeze

    FIRST_PARTY_AS_THIRD_PARTY_OVERRIDES = [
      'Audit Request',
      'HAIMS STR Follow-up',
      'NG1 - National Guard Records Request',
      'PMR Pending',
      'Prison Development - 21-4193 Needed',
      'Proof of service (DD214, etc.)',
      'RV1 - Reserve Records Request',
      'VHA Outpatient Treatment Records (10-7131)'
    ].freeze

    # Evidence requests that are first-party (NEEDED_FROM_YOU), keyed by `displayName`.
    # Used to set an `isFirstParty` flag on each tracked item so CST can render correct
    # closed-state content after `status` mutates.
    # Source of truth is column D of the Evidence Request Tracker (internal SharePoint document).
    FIRST_PARTY_EVIDENCE_REQUESTS = [
      '1151 -need date, location, description of incident',
      '21-4142',
      '21-4142 incomplete - need provider address',
      '21-4142/21-4142a',
      '21-4142a',
      '90 days service, medical and income',
      'Address of dependent needed',
      'Amended Death Certificate',
      'AO - Blue Water Notice',
      'AO - Explain how exposed to herbicides',
      'AO - Exposure General Notice',
      'AO - Exposure General Notice-PMC',
      'AO - Tell us if VA treatment provided',
      'AO-med evid of disab fm herbicide needed',
      'AO-not a recognized condition',
      'AO-submit evidence of Vietnam service',
      'AO-Tell us specific disability fm herbicides',
      'Application not signed - signature needed',
      'ASB - tell us specific disability fm asbestos exposure',
      'ASB - tell us where, when, how exposed',
      'ASB-medical evid of disease (biopsy) needed',
      'ASB-tell us specific disability fm asbestos exposure',
      'Asbestos Development Language Missing From VBMS',
      'Automated 5103 Notice Response',
      'Chemical Exposure Clarification',
      'Claimant - date of current marriage needed',
      'Claimant - date of marriage needed',
      'Claimant Date of Termination of Marriage',
      'Claimant marital history inconsistent - need 21-686c',
      'Claimant marital history inconsistent - need proof',
      'Clarification of Claimed Issue',
      'Clarification of Income',
      'Clarify Intent To Withdraw',
      'Common Law - 21-4170 fm claimant needed',
      'Common Law - 21-4170 fm spouse needed',
      'Common Law - 21-4171s fm 2 others',
      'Continuous cohab unknown - verify lived together',
      'Continuous cohabitation',
      'Death Certificate',
      'Death Certificate Missing Cause of Death',
      'Death certification request Generic',
      'Deemed valid marriage',
      'Dependent date of birth needed',
      'Dependent location of birth needed',
      'Dependent Social Security Number (SSN) needed',
      'DIC - Disability Not Specified',
      'DIC Disability Not Decided-No SC',
      'DIC Disability Not Decided-S/C',
      'DIC Disability Not Specified-No SC',
      'Direct deposit/EFT solicitation',
      'Disability severance pay amount',
      'Due Process',
      'EFT - Treasury Mandate Notification',
      'Employment info needed - 21-4192 to veteran',
      'Evidence needed to establish child, birth cert, etc.',
      'Evidence Needed to Establish Child, Birth Cert, Etc. (CPD)',
      'Evidence not acceptable, birth certificate needed',
      'Evidence of adoption needed',
      'FDC Program Exclusion',
      'FINAL NOTIFICATION - DEVELOPMENT LETTER',
      'Fire related service - NAF13055 needed',
      'Fire Related Service- NAF 13055 Needed',
      'Form incomplete - items checked in red needed',
      'General Records Request (Non-Medical)',
      'GW - Earliest manifestations/evid of illness',
      'GW - Registry exam?',
      'GW - Tell us specific disability fm GW',
      'GW-3.320 evidence of SW Asia svc needed',
      'GW-evidence of SW Asia service needed',
      'GW-registry exam?',
      'GW-tell us specific disability fm GW',
      'Helpless - child mbr household before 18 needed',
      'Helpless - med evid and age disabled needed',
      'Hepatitis C Questionnaire',
      'History of prior marriages of claimant needed',
      'History of prior marriages of spouse needed',
      'Marriage certificate',
      'Marriage reported - 21-686c needed',
      'Med expenses solicit - 21-8416 needed',
      'Medical evidence for pension',
      'MG- circumstances of exposure',
      'MG-medical evidence',
      'Military retired pay - describe if receiving',
      'Military Retired Pay Information',
      'Multiple periods of service - proof required',
      'Name of dental disability needed',
      'Name of disability needed',
      'Need VAF 21P-0969',
      'Notice invalid signature',
      'Parental Dependency',
      'Parental relationship with child needed or clarification',
      'Primary Residence Information',
      'Private provider charges for records',
      'Private provider requires spec. release',
      'PTSD - Follow Up for Stressor Details',
      'PTSD - Need stressor details/med evid combat-related incdnt',
      'PTSD - Need stressor details/med evid of stressful incdnt',
      'PTSD - Need stressor details/med evid personal trauma incdnt',
      'PTSD - request address of Vet Center attended',
      'PTSD- fear w/hostile mil/terrorist (original)',
      'PTSD-Stressor detail/med evid - fear w/hostile mil/terrorist',
      'RADIATION - medical evid of disease needed',
      'Radiation-tell us how you were exposed',
      'Radiation-tell us specific disability fm exposure',
      'Recent treatment for claimed conditions',
      'Remarriage - Surviving Spouse',
      'Request 686C Generic',
      'Request discharge document or completion of NAF 13075',
      'Request Service Medical Records from Veteran',
      'Request Service Treatment Records from Veteran',
      'Reserve or Guard service claimed - unit info needed',
      'SC death - request med evid',
      'School - VA Form 21-674 needed',
      'Secondary disability',
      'Send form - complete enclosed form',
      'Separation pay amount',
      'SMRs not available - substitute documents needed',
      'Special Monthly Pension',
      'Spouse - date of divorce needed',
      'Spouse - marital history inconsistent - need proof',
      'Spouse or Claimant - proof of terminated marriage(s)',
      'STRs not available - substitute documents needed',
      'Submit buddy statement(s)',
      'Unemployability - 21-8940 needed and 4192(s) requested',
      'Unemployability - self employed',
      'Upload Failure',
      'VA Form 21 4142 Not HIPAA Compliant',
      'VA Form 21-2680 - unsigned',
      'VA Form 21P-0969 Form Incomplete',
      "VAF 21-4142 for vet's treatment records/autopsy for death c",
      "VAF 21-4142 for vet's treatment records/autopsy for death claims",
      'Wages needed',
      'Waiting for a reply from claimant',
      'Waiting for reply from claimant'
    ].to_set.freeze
  end
end
