# frozen_string_literal: true

class SourceAppMiddleware
  MODULES_APP_NAMES = Set.new %w[
    appeals_api
    apps_api
    claims_api
    coronavirus-research
    mobile
    openid_auth
    test_user_dashboard
  ].freeze

  OTHER_APP_NAMES = Set.new %w[
    unknown
    undefined
  ].freeze

  # NOTE: Corresponds to the HTTP_SOURCE_APP_NAME header
  # Allowlist of vets-website app names. List was generated by running
  # `yarn apps` or `npm run apps` from inside the vets-website dir
  FRONT_END_APP_NAMES = Set.new [
    '526EZ-all-claims-v2',
    'sco',
    'your-recommended-benefits',
    '21-4140-eq',
    'mhv-supply-reordering',
    'download',
    'onramp',
    '10215-edu-benefits',
    '10282-edu-benefits',
    '10216-edu-benefits',
    '8794-edu-benefits',
    '1919-edu-benefits',
    'form-upload-flow',
    'new-chapter-36-form',
    '0247-pmc',
    '0803-edu-benefits',
    '0810-edu-benefits',
    '0839-edu-benefits',
    '0845-auth-disclose',
    '0976-edu-benefits',
    '0989-edu-benefits',
    '10272-edu-benefits',
    '10275-edu-benefits',
    '10278-edu-benefits',
    '10297-edu-benefits',
    '0996-higher-level-review',
    '10-10d-extended',
    '1010cg-application-caregiver-assistance',
    '10182-board-appeal',
    '10203-edu-benefits',
    '10206-pa',
    '10207-pp',
    '10210-lay-witness-statement',
    '10-7959a',
    '10-7959C',
    '10-8678',
    '1330m2-medallions',
    '1330m-medallions',
    '1990ez-edu-benefits',
    '1995-edu-benefits',
    '21-0779-nursing-home-information',
    '21-0788',
    '21-0966-intent-to-file-a-claim',
    '21-0972-alternate-signer',
    '21-2680-house-bound-status',
    '21-4140',
    '21-4142-medical-release',
    '21-4192-employment-information',
    '21-4502',
    '21-8940',
    '21p-0537',
    '21P-0847-substitute-claimant',
    '21p-530a-interment-allowance',
    '21P-601',
    '25-8832-planning-and-career-guidance',
    '28-1900-chapter-31',
    '4138-ss',
    '4555-adapted-housing',
    '526EZ-all-claims',
    '686C-674-v2',
    '995-supplemental-claim',
    'appoint-a-representative',
    'ask-a-question',
    'ask-va',
    'auth',
    'avs',
    'burials-ez',
    'check-in',
    'claims-status',
    'coe',
    'coe-status',
    'combined-debt-portal',
    'covid19screen',
    'dashboard',
    '0538-dependents-verification',
    'dependents-view-dependents',
    'dhp-consent-flow',
    'discharge-upgrade-instructions',
    'discover-your-benefits',
    'dispute-debt',
    'ds-playground',
    'ds-v3-playground',
    'education-letters',
    'enrollment-verification',
    'ezr',
    'facilities',
    'feedback-tool',
    'find-a-representative',
    'fmp-cover-sheet',
    'form-renderer',
    'fry-dea',
    'gi',
    'hca',
    'health-care-supply-reordering',
    'income-and-asset-statement',
    'income-limits',
    'letters',
    'login-page',
    'medical-expense-report',
    'medical-records',
    'medications',
    'messages',
    'mhv-landing-page',
    'mhv-secure-messaging',
    'mock-form',
    'mock-form-patterns-v3',
    'mock-simple-forms-patterns',
    'mock-sip-form',
    'office-directory',
    'pact-act',
    'pensions',
    'post-911-gib-status',
    'pre-check-in',
    'pre-need',
    'pre-need-integration',
    'profile',
    'proxy-rewrite',
    'public-outreach-materials',
    'rated-disabilities',
    'representative',
    'representative-form-upload',
    'representative-21a',
    'request-debt-help-form-5655',
    'resources-and-support',
    'sahg',
    'search',
    'sign-in-health-portal',
    'survivor-dependent-education-benefit-22-5490',
    'survivors-benefits',
    'static-pages',
    'terms-of-use',
    'toe',
    'travel-claim',
    'travel-pay',
    'vaos',
    'vass',
    'verify',
    'verify-your-enrollment',
    'veteran-id-card',
    'view-payments',
    'virtual-agent',
    'welcome-va-setup-review-information',
    'yellow-ribbon',
    'ch31-eligibility-entitlement',
    'track-your-vre-benefits'
  ].freeze

  MOBILE_APP_NAMES = Set.new %w[
    va-health-benefits-app
  ].freeze

  SOURCE_APP_NAMES = FRONT_END_APP_NAMES + MOBILE_APP_NAMES + MODULES_APP_NAMES + OTHER_APP_NAMES

  def initialize(app)
    @app = app
  end

  def call(env)
    source_app = env['HTTP_SOURCE_APP_NAME']

    if source_app.nil?
      source_app = 'not_provided'
    elsif SOURCE_APP_NAMES.exclude?(source_app)
      # TODO: - Seek alternative notification approach. It must be done in a rate-limited way
      #        so as not to allow for a malicious client to overflow worker queues
      Rails.logger.warn "Unrecognized value for HTTP_SOURCE_APP_NAME request header... [#{source_app}]"
      source_app = 'not_in_allowlist'
    end

    env['SOURCE_APP'] = source_app
    @app.call(env)
  end
end
