---
sign_in:
  event_type: sign_in
  details: Sign in on VA.gov
update_direct_deposit:
  event_type: profile
  details: Update direct deposit
update_email_address:
  event_type: profile
  details: Update email address
update_mailing_address:
  event_type: profile
  details: Update mailing address
update_phone_number:
  event_type: profile
  details: Update phone number

