# frozen_string_literal: true

require 'rails_helper'
require 'unified_health_data/adapters/vital_adapter'
require 'unified_health_data/models/vital'

RSpec.describe 'VitalAdapter' do
  let(:adapter) { UnifiedHealthData::Adapters::VitalAdapter.new }
  let(:vital_sample_response) do
    JSON.parse(Rails.root.join(
      'spec', 'fixtures', 'unified_health_data', 'vitals_example.json'
    ).read)
  end

  before do
    allow(UnifiedHealthData::Vital).to receive(:new).and_call_original
    allow(Rails.logger).to receive(:warn)
  end

  describe '#parse_single_vital' do
    describe 'formatting blood pressure' do
      it 'returns the expected fields for VistA blood pressure record' do
        record = vital_sample_response['vista']['entry'][5]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'ab512a04-f9d6-4100-972c-6a5364451c54',
            'name' => 'Blood pressure',
            'type' => 'BLOOD_PRESSURE',
            'date' => '2024-12-17T16:03:16Z',
            'measurement' => '112/80',
            'location' => 'GREELEY NUTRITION',
            'notes' => []
          }
        )
      end

      it 'returns the expected fields for OH blood pressure record' do
        record = vital_sample_response['oracle-health']['entry'][6]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'BP-15249666629-15249666631',
            'name' => 'Blood pressure',
            'type' => 'BLOOD_PRESSURE',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '112/80',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => []
          }
        )
      end
    end

    describe 'formatting height' do
      it 'returns the expected fields for VistA height record' do
        record = vital_sample_response['vista']['entry'][2]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => '3f951c1d-406f-44e0-a922-bf6db786e652',
            'name' => 'Height',
            'type' => 'HEIGHT',
            'date' => '2024-12-05T16:24:26Z',
            'measurement' => '5 feet, 5.0 inches',
            'location' => 'BAYPINES',
            'notes' => []
          }
        )
      end

      it 'returns the expected fields for OH height record' do
        record = vital_sample_response['oracle-health']['entry'][7]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'VS-15249666623',
            'name' => 'Height/length measured',
            'type' => 'HEIGHT',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '5 feet, 4.6 inches',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => []
          }
        )
      end
    end

    describe 'formatting temperature' do
      it 'returns the expected fields for VistA temperature record' do
        record = vital_sample_response['vista']['entry'][4]
        parsed_vital = adapter.parse_single_vital(record)
        expect(parsed_vital).to have_attributes(
          {
            'id' => 'fa104e74-21b5-4ee0-9e15-0f391093aaa7',
            'name' => 'Temperature',
            'type' => 'TEMPERATURE',
            'date' => '2025-01-29T14:56:17Z',
            'measurement' => '113.0 °F',
            'location' => 'CHYTEST PRO',
            'notes' => []
          }
        )
      end

      it 'returns the expected fields for OH temperature record' do
        record = vital_sample_response['oracle-health']['entry'][3]
        parsed_vital = adapter.parse_single_vital(record)
        expect(parsed_vital).to have_attributes(
          {
            'id' => 'VS-15249666641',
            'name' => 'Temperature tympanic',
            'type' => 'TEMPERATURE',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '98.8 °F',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => []
          }
        )
      end
    end

    describe 'formatting weight' do
      it 'returns the expected fields for record with multiple weight measurements (and notes)' do
        record = vital_sample_response['oracle-health']['entry'][2]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'VS-15249708684',
            'name' => 'Weight dosing',
            'type' => 'WEIGHT',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '150.8 pounds',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => ['Result generated by automated process based on measured weight.']
          }
        )
      end

      it 'returns the expected fields for VistA weight record' do
        record = vital_sample_response['vista']['entry'][0]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'be3724c0-f9e2-4e6a-b37e-366aca305613',
            'name' => 'Weight',
            'type' => 'WEIGHT',
            'date' => '2025-08-22T22:16:24Z',
            'measurement' => '165.4 pounds',
            'location' => 'CHY ANOTHER TEST CLINIC',
            'notes' => []
          }
        )
      end
    end

    describe 'formatting pulse' do
      it 'returns the expected fields for VistA pulse record' do
        record = vital_sample_response['vista']['entry'][3]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'bbf83fa7-db79-4139-b78d-bbfcf48c5eae',
            'name' => 'Pulse',
            'type' => 'PULSE',
            'date' => '2025-01-29T14:56:17Z',
            'measurement' => '80 beats per minute',
            'location' => 'CHYTEST PRO',
            'notes' => []
          }
        )
      end

      it 'returns the expected fields for OH pulse record' do
        record = vital_sample_response['oracle-health']['entry'][5]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'VS-15249666635',
            'name' => 'Peripheral pulse rate',
            'type' => 'PULSE',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '87 beats per minute',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => []
          }
        )
      end
    end

    describe 'formatting pulse oximetry' do
      it 'returns the expected fields for VistA pulse oximetry record' do
        record = vital_sample_response['vista']['entry'][6]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => '5751a572-5e53-44d8-8c29-d7d1477d31aa',
            'name' => 'Pulse oximetry',
            'type' => 'PULSE_OXIMETRY',
            'date' => '2024-12-17T16:03:16Z',
            'measurement' => '97%',
            'location' => 'GREELEY NUTRITION',
            'notes' => []
          }
        )
      end

      it 'returns the expected fields for OH pulse oximetry record' do
        record = vital_sample_response['oracle-health']['entry'][1]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'VS-PO-15249666639',
            'name' => 'Spo2',
            'type' => 'PULSE_OXIMETRY',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '99%',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => []
          }
        )
      end
    end

    describe 'formatting respiration rate' do
      it 'returns the expected fields for VistA respiration record' do
        record = vital_sample_response['vista']['entry'][7]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'a3356389-2d2d-409d-bf0f-5da95229012e',
            'name' => 'Respiration',
            'type' => 'RESPIRATION',
            'date' => '2024-12-17T16:03:16Z',
            'measurement' => '18 breaths per minute',
            'location' => 'GREELEY NUTRITION',
            'notes' => []
          }
        )
      end

      it 'returns the expected fields for OH respiration record' do
        record = vital_sample_response['oracle-health']['entry'][4]
        parsed_vital = adapter.parse_single_vital(record)

        expect(parsed_vital).to have_attributes(
          {
            'id' => 'VS-15249666637',
            'name' => 'Respiratory rate',
            'type' => 'RESPIRATION',
            'date' => '2025-07-24T18:23:00.000Z',
            'measurement' => '19 breaths per minute',
            'location' => '668 Mann-Grandstaff WA VA Medical Center',
            'notes' => []
          }
        )
      end
    end

    describe 'logging unknown LOINC codes' do
      it 'logs a warning when a vital record has an unknown LOINC code but still parses record' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'a3356389-2d2d-409d-bf0f-5da95229012e',
            'contained' => [
              {
                'resourceType' => 'Location',
                'id' => 'location-873',
                'name' => 'GREELEY NUTRITION'
              }
            ],
            'code' => {
              'coding' => [
                { 'system' => 'http://loinc.org', 'code' => '12345-0', 'display' => 'Unknown Vital' }
              ],
              'text' => 'Unknown Vital Measurement'
            },
            'effectiveDateTime' => '2024-12-17T16:03:16Z',
            'performer' => [
              {
                'extension' => [
                  {
                    'url' => 'http://hl7.org/fhir/StructureDefinition/alternate-reference',
                    'valueReference' => {
                      'reference' => '#location-873'
                    }
                  }
                ],
                'display' => 'Location 873'
              }
            ],
            'valueQuantity' => {
              'value' => 18,
              'unit' => '/min',
              'system' => 'http://unitsofmeasure.org',
              'code' => '/min'
            }
          }
        }

        expect(Rails.logger).to receive(:warn).with(/\["code: 12345-0, display: Unknown Vital"\]/i)

        parsed_vital = adapter.parse_single_vital(record)
        expect(parsed_vital).to have_attributes(
          {
            'id' => 'a3356389-2d2d-409d-bf0f-5da95229012e',
            'name' => 'Unknown vital measurement',
            'type' => 'OTHER',
            'date' => '2024-12-17T16:03:16Z',
            'measurement' => '18',
            'location' => 'GREELEY NUTRITION',
            'notes' => []
          }
        )
      end

      it 'logs a warning when a vital record has an missing LOINC code but parses is available' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => '12345',
            'code' => {
              'coding' => [],
              'text' => 'Missing vital measurement'
            },
            'valueQuantity' => {
              'value' => 18,
              'unit' => '/min',
              'system' => 'http://unitsofmeasure.org',
              'code' => '/min'
            }
          }
        }

        expect(Rails.logger).to receive(:warn).with(
          /Missing vital measurement/i
        )

        parsed_vital = adapter.parse_single_vital(record)
        expect(parsed_vital).to have_attributes(
          {
            'id' => '12345',
            'name' => 'Missing vital measurement',
            'type' => 'OTHER',
            'date' => nil,
            'measurement' => '18',
            'location' => nil,
            'notes' => []
          }
        )
      end
    end
  end

  describe 'entered-in-error filtering' do
    let(:user) { build(:user, :loa3, icn: '1000123456V123456') }
    let(:adapter_with_user) { UnifiedHealthData::Adapters::VitalAdapter.new(user:) }

    let(:normal_record) do
      {
        'resource' => {
          'resourceType' => 'Observation',
          'id' => 'normal-vital',
          'status' => 'final',
          'code' => { 'coding' => [{ 'code' => '29463-7' }], 'text' => 'Weight' },
          'valueQuantity' => { 'value' => 180, 'unit' => 'lb_av' }
        }
      }
    end

    let(:entered_in_error_record) do
      {
        'resource' => {
          'resourceType' => 'Observation',
          'id' => 'error-vital',
          'status' => 'entered-in-error',
          'code' => { 'coding' => [{ 'code' => '29463-7' }], 'text' => 'Weight' },
          'valueQuantity' => { 'value' => 999, 'unit' => 'lb_av' }
        }
      }
    end

    before do
      allow(Flipper).to receive(:enabled?).and_return(false)
    end

    it 'filters out records with entered-in-error status' do
      result = adapter_with_user.parse([entered_in_error_record])
      expect(result).to be_empty
    end

    it 'keeps records with non-error status' do
      result = adapter_with_user.parse([normal_record])
      expect(result.length).to eq(1)
    end

    it 'filters entered-in-error but keeps normal records in mixed list' do
      result = adapter_with_user.parse([normal_record, entered_in_error_record])
      expect(result.length).to eq(1)
      expect(result.first.id).to eq('normal-vital')
    end

    context 'diagnostic logging for filtered records' do
      before do
        allow(Flipper).to receive(:enabled?)
          .with(:mhv_medical_records_vitals_diagnostic, user)
          .and_return(true)
        allow(StatsD).to receive(:increment)
      end

      it 'logs diagnostic message when a vital is filtered' do
        expect(Rails.logger).to receive(:info).with(
          hash_including(
            service: 'medical_records',
            resource: 'vitals',
            action: 'filter',
            record_id: 'error-vital',
            status: 'entered-in-error',
            reason: 'entered_in_error',
            log_level_context: 'diagnostic'
          )
        )

        adapter_with_user.parse([entered_in_error_record])
      end

      it 'increments StatsD counter when a vital is filtered' do
        adapter_with_user.parse([entered_in_error_record])

        expect(StatsD).to have_received(:increment).with(
          'unified_health_data.vital.filtered_observation',
          tags: ['reason:entered_in_error']
        )
      end

      it 'does not log or increment when no records are filtered' do
        expect(Rails.logger).not_to receive(:info).with(
          hash_including(resource: 'vitals', action: 'filter')
        )
        expect(StatsD).not_to receive(:increment).with(
          'unified_health_data.vital.filtered_observation', anything
        )

        adapter_with_user.parse([normal_record])
      end
    end
  end

  describe 'weight dosing filtering' do
    let(:user) { build(:user, :loa3, icn: '1000123456V123456') }
    let(:adapter_with_user) { UnifiedHealthData::Adapters::VitalAdapter.new(user:) }

    let(:weight_dosing_record) do
      {
        'resource' => {
          'resourceType' => 'Observation',
          'id' => 'VS-weight-dosing',
          'status' => 'final',
          'code' => { 'coding' => [{ 'code' => '29463-7' }], 'text' => 'Weight dosing' },
          'valueQuantity' => { 'value' => 150, 'unit' => 'lb_av' },
          'note' => [{ 'text' => 'Result generated by automated process based on measured weight.' }]
        }
      }
    end

    let(:weight_measured_record) do
      {
        'resource' => {
          'resourceType' => 'Observation',
          'id' => 'VS-weight-measured',
          'status' => 'final',
          'code' => { 'coding' => [{ 'code' => '29463-7' }], 'text' => 'Weight measured' },
          'valueQuantity' => { 'value' => 150, 'unit' => 'lb_av' }
        }
      }
    end

    let(:vista_weight_record) do
      {
        'resource' => {
          'resourceType' => 'Observation',
          'id' => 'vista-weight',
          'status' => 'final',
          'code' => { 'coding' => [{ 'code' => '29463-7' }], 'text' => 'Weight' },
          'valueQuantity' => { 'value' => 165, 'unit' => 'lb_av' }
        }
      }
    end

    before do
      allow(Flipper).to receive(:enabled?).and_return(false)
    end

    it 'filters out Oracle Health weight dosing records' do
      result = adapter_with_user.parse([weight_dosing_record])
      expect(result).to be_empty
    end

    it 'keeps weight measured records' do
      result = adapter_with_user.parse([weight_measured_record])
      expect(result.length).to eq(1)
      expect(result.first.id).to eq('VS-weight-measured')
    end

    it 'keeps VistA weight records' do
      result = adapter_with_user.parse([vista_weight_record])
      expect(result.length).to eq(1)
      expect(result.first.id).to eq('vista-weight')
    end

    it 'filters weight dosing but keeps other weight records in mixed list' do
      result = adapter_with_user.parse([weight_dosing_record, weight_measured_record, vista_weight_record])
      expect(result.length).to eq(2)
      expect(result.map(&:id)).to contain_exactly('VS-weight-measured', 'vista-weight')
    end

    it 'handles case-insensitive matching for Weight Dosing' do
      uppercase_dosing = weight_dosing_record.deep_dup
      uppercase_dosing['resource']['code']['text'] = 'WEIGHT DOSING'
      result = adapter_with_user.parse([uppercase_dosing])
      expect(result).to be_empty
    end
  end

  describe 'null/nil exception guards' do
    let(:adapter_instance) { UnifiedHealthData::Adapters::VitalAdapter.new }

    before { allow(Rails.logger).to receive(:warn) }

    # 1a. get_name — .humanize on nil
    describe '#parse_single_vital — get_name nil guard (fix 1a)' do
      it 'does not crash when code.text is nil' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1a-1',
            'code' => {
              'coding' => [{ 'code' => '29463-7', 'display' => 'Weight' }]
            },
            'valueQuantity' => { 'value' => 180, 'unit' => 'lb_av' }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.name).to eq('Weight')
      end

      it 'does not crash when both code.text and coding display are nil' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1a-2',
            'code' => {
              'coding' => [{ 'code' => '29463-7' }]
            },
            'valueQuantity' => { 'value' => 180 }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.name).to eq('')
      end
    end

    # 1b. get_measurements — valueQuantity nil guard
    describe '#parse_single_vital — nil valueQuantity (fix 1b)' do
      it 'does not crash when valueQuantity is nil' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1b',
            'code' => {
              'coding' => [{ 'code' => '29463-7' }],
              'text' => 'Weight'
            }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end
    end

    # 1c. get_measurements — string interpolation always truthy
    describe '#parse_single_vital — nil valueQuantity.value (fix 1c)' do
      it 'returns nil measurement when valueQuantity.value is nil' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1c',
            'code' => {
              'coding' => [{ 'code' => '8867-4' }],
              'text' => 'Pulse'
            },
            'valueQuantity' => { 'unit' => 'bpm' }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end
    end

    # 1d. format_blood_pressure — empty hash truthy
    describe '#parse_single_vital — blood pressure with no matching components (fix 1d)' do
      it 'returns nil measurement when neither systolic nor diastolic components match' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1d',
            'code' => {
              'coding' => [{ 'code' => '85354-9' }],
              'text' => 'Blood pressure'
            },
            'component' => [
              {
                'code' => { 'coding' => [{ 'code' => 'UNKNOWN' }] },
                'valueQuantity' => { 'value' => 120 }
              }
            ]
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end

      it 'returns nil when systolic found but valueQuantity missing value' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1d-2',
            'code' => {
              'coding' => [{ 'code' => '85354-9' }],
              'text' => 'Blood pressure'
            },
            'component' => [
              {
                'code' => { 'coding' => [{ 'code' => '8480-6' }] },
                'valueQuantity' => {}
              },
              {
                'code' => { 'coding' => [{ 'code' => '8462-4' }] },
                'valueQuantity' => { 'value' => 80 }
              }
            ]
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end
    end

    # 1e. format_height — nil value before divmod
    describe '#parse_single_vital — height with nil valueQuantity (fix 1e)' do
      it 'returns nil measurement when height valueQuantity.value is nil' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1e',
            'code' => {
              'coding' => [{ 'code' => '8302-2' }],
              'text' => 'Height'
            },
            'valueQuantity' => {}
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end
    end

    # 1f. format_extension_measurements — find returns nil
    describe '#parse_single_vital — extension measurements with no matching entry (fix 1f)' do
      it 'returns nil when height extension has no matching [in_i] code' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1f',
            'code' => {
              'coding' => [{ 'code' => '8302-2' }],
              'text' => 'Height'
            },
            'valueQuantity' => {
              'extension' => [
                { 'valueQuantity' => { 'code' => '[cm]', 'value' => 165 } }
              ]
            }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end

      it 'returns nil when weight extension has no matching [lb_av] code' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1f-w',
            'code' => {
              'coding' => [{ 'code' => '29463-7' }],
              'text' => 'Weight'
            },
            'valueQuantity' => {
              'extension' => [
                { 'valueQuantity' => { 'code' => '[kg]', 'value' => 75 } }
              ]
            }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end

      it 'returns nil when temperature extension has no matching [degF] code' do
        record = {
          'resource' => {
            'resourceType' => 'Observation',
            'id' => 'v-1f-t',
            'code' => {
              'coding' => [{ 'code' => '8310-5' }],
              'text' => 'Temperature'
            },
            'valueQuantity' => {
              'extension' => [
                { 'valueQuantity' => { 'code' => '[degC]', 'value' => 37 } }
              ]
            }
          }
        }
        vital = adapter_instance.parse_single_vital(record)
        expect(vital.measurement).to be_nil
      end
    end

    # 1g. find_contained — nil unless without return
    describe '#find_contained — return nil for mismatched type (fix 1g)' do
      it 'returns nil when contained resource has wrong type for hash reference' do
        record = {
          'contained' => [
            { 'id' => 'prac-1', 'resourceType' => 'Practitioner', 'name' => 'Dr. Smith' }
          ]
        }
        result = adapter_instance.send(:find_contained, record, '#prac-1', 'Location')
        expect(result).to be_nil
      end
    end
  end
end
