# frozen_string_literal: true

require_relative 'vba_10_8678_ibm_converter/helpers'

module SimpleFormsApi
  module Mms
    module VBA108678IbmConverter
      extend Helpers

      MAX_APPLIANCES = 5

      MAPPINGS = {
        # --- Section 1-4b: Veteran identifiers & contact ---
        'VETERAN_NAME' => ->(form) { full_name(form) },
        'VETERAN_SSN' => ->(form) { normalize_ssn(form.data['ssn']) },
        'VETERAN_ADDRESS_FULL_BLOCK' => ->(form) { veteran_address_block(form) },
        'VETERAN_NEW_ADDRESS' => ->(form) { bool_to_checkbox(form.data['new_address']) },
        'DAY_PHONE_NUMBER' => ->(form) { phone_digits(form.data['phone']) },
        'EVENING_PHONE_NUMBER' => ->(form) { phone_digits(form.data['evening_phone']) },
        'EMAIL' => ->(form) { form.data['email_address'] || '' },

        # --- Section 5: Calendar year (derived from signature year if not explicit) ---
        'APP_CALENDAR_YEAR' => ->(form) { app_calendar_year(form) },

        # --- Section 6: Veteran signature ---
        'VETERAN_SIGNATURE' => ->(form) { signature_checkbox(form) },
        'DATE_OF_VETERAN_SIGNATURE' => ->(form) { format_iso_date(form.data['signature_date']) },

        # --- Section 12: Amount of clothing allowances (For VA Use Only) ---
        'ELIGIBLE' => ->(form) { allowance_value(form, 'eligible') },
        'NOT_ELIGIBLE' => ->(form) { allowance_value(form, 'not_eligible') },
        'UPPER_EXTREMITY' => ->(form) { allowance_value(form, 'upper_extremity') },
        'LOWER_EXTREMITY' => ->(form) { allowance_value(form, 'lower_extremity') },

        # --- Section 13: Exam date ---
        'EXAM_DATE' => ->(form) { format_iso_date(form.data['exam_date']) },

        # --- Section 14: Notes ---
        'NOTES' => ->(form) { form.data['notes'] || '' },

        # --- Section 15: Generated by (For VA Use Only) ---
        'GENERATED_BY' => ->(form) { form.data['generated_by'] || '' },
        'DATE_GENERATED_BY' => ->(form) { format_iso_date(form.data['date_generated_by']) },

        # --- Section 16: Authorized by (For VA Use Only) ---
        'AUTHORIZED_BY' => ->(form) { form.data['authorized_by'] || '' },
        'DATE_AUTHORIZED_BY' => ->(form) { format_iso_date(form.data['date_authorized_by']) }
      }.freeze

      def self.convert(form)
        result = MAPPINGS.transform_values { |proc| proc.call(form) }
        appliances = Array(form.data['appliances']).first(MAX_APPLIANCES)

        (1..MAX_APPLIANCES).each do |i|
          appliance = appliances[i - 1] || {}
          result.merge!(appliance_fields(appliance, i))
        end

        result.sort.to_h
      end
    end
  end
end
