name: Push CODEOWNERS to Platform Atlas
on:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - '.github/CODEOWNERS'
permissions:
  id-token: write
  contents: read
  checks: write
jobs:
  copy-codeowners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
          aws-region: "us-gov-west-1"
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Get bot token from Parameter Store
        uses: department-of-veterans-affairs/action-inject-ssm-secrets@32c55d942e380d6819aef96bc01b0eabb2159715 # latest
        with:
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN

      - name:  Check codeowner changes
        id: check-codeowner-changes
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: |
            .github/CODEOWNERS

      - name: Pushes CODEOWNERS updates to Atlas
        if: steps.check-codeowner-changes.outputs.any_changed == 'true'
        uses: dmnemec/copy_file_to_another_repo_action@bbebd3da22e4a37d04dca5f782edd5201cb97083 # main
        env:
          API_TOKEN_GITHUB: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
        with:
          source_file: '.github/CODEOWNERS'
          destination_repo: 'department-of-veterans-affairs/platform-atlas'
          destination_folder: '/lib/codeowners/vets-api'
          destination_branch: 'master'
          user_email: '70344339+va-vsp-bot@users.noreply.github.com'
          user_name: 'va-vsp-bot'
          commit_message: 'Auto update Atlas with Vets-API CODEOWNERS'
