name: Danger
on: [pull_request]
permissions:
  contents: read
  id-token: write
  issues: read
  pull-requests: write
  statuses: write
jobs:
  danger:
    name: Danger

    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DANGER_GITHUB_API_BASE_URL: https://va.ghe.com/api/v3

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
          aws-region: us-gov-west-1

      - uses: software/action-inject-ssm-secrets@47689845c2a46848eb5455078d9261c8dfe5e521 # latest
        with:
          ssm_parameter: /dsva-vagov/vets-api/prod/env_vars/BUNDLE_ENTERPRISE__CONTRIBSYS__COM
          env_variable_name: BUNDLE_ENTERPRISE__CONTRIBSYS__COM

      - name: Generate cross-repo token for gems
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ vars.GEM_APP_CLIENT_ID }}
          private-key: ${{ secrets.GEM_APP_PRIVATE_KEY }}
          owner: software
          github-api-url: https://va.ghe.com/api/v3

      - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1
        env:
          BUNDLE_VA__GHE__COM: x-access-token:${{ steps.app-token.outputs.token }}
        with:
          bundler-cache: true

      - name: Run Danger
        run: bundle exec danger --verbose

      - name: Add Danger Label
        if: ${{ failure() }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['danger-alert'],
            })
