name: Security Alert Notifications

on:
  schedule:
    - cron: '3 17 * * 1-5' # Weekdays 17:03 UTC (~12–1 PM ET, depending on DST)
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6
        with:
          role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
          aws-region: us-gov-west-1

      - name: Get Slack bot token
        uses: software/action-inject-ssm-secrets@47689845c2a46848eb5455078d9261c8dfe5e521 # latest
        with:
          ssm_parameter: /devops/github_actions_slack_bot_user_token
          env_variable_name: SLACK_BOT_TOKEN

      - name: Check and notify security alerts
        uses: software/vsp-github-actions/security-alert-slack-notify@e757949598396a97cdffd9a9dd0536846ffb104b # main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          slack_bot_token: ${{ env.SLACK_BOT_TOKEN }}
          channel_id: 'C02RLAUM2LV'
          alert_types: 'code_scanning,secret_scanning'
