name: Validate Files DataDog Service Catalog Files
# This workflow has the opposite filter as validate-datadog-changes.yml. See .github/scripts/validate-datadog-yaml/README.md for more information
on:
  pull_request:
    paths-ignore:
      - "datadog-service-catalog/**.yml"

permissions:
  contents: read

jobs:
  validate_files:
    runs-on: ubuntu-latest
    name: echo Pass
    steps:
      - run: echo "PASS -- No files to validate."
